// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: proto/klara/mx/v1/mail.proto

package klarapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailStatus int32

const (
	MailStatus_mail_pending    MailStatus = 0
	MailStatus_mail_processing MailStatus = 1
	MailStatus_mail_done       MailStatus = 2
	MailStatus_mail_error      MailStatus = -1
)

// Enum value maps for MailStatus.
var (
	MailStatus_name = map[int32]string{
		0:  "mail_pending",
		1:  "mail_processing",
		2:  "mail_done",
		-1: "mail_error",
	}
	MailStatus_value = map[string]int32{
		"mail_pending":    0,
		"mail_processing": 1,
		"mail_done":       2,
		"mail_error":      -1,
	}
)

func (x MailStatus) Enum() *MailStatus {
	p := new(MailStatus)
	*p = x
	return p
}

func (x MailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_klara_mx_v1_mail_proto_enumTypes[0].Descriptor()
}

func (MailStatus) Type() protoreflect.EnumType {
	return &file_proto_klara_mx_v1_mail_proto_enumTypes[0]
}

func (x MailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailStatus.Descriptor instead.
func (MailStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{0}
}

type MailType int32

const (
	MailType_mail_type_unknown  MailType = 0
	MailType_mail_type_inbound  MailType = 1
	MailType_mail_type_outbound MailType = 2
)

// Enum value maps for MailType.
var (
	MailType_name = map[int32]string{
		0: "mail_type_unknown",
		1: "mail_type_inbound",
		2: "mail_type_outbound",
	}
	MailType_value = map[string]int32{
		"mail_type_unknown":  0,
		"mail_type_inbound":  1,
		"mail_type_outbound": 2,
	}
)

func (x MailType) Enum() *MailType {
	p := new(MailType)
	*p = x
	return p
}

func (x MailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_klara_mx_v1_mail_proto_enumTypes[1].Descriptor()
}

func (MailType) Type() protoreflect.EnumType {
	return &file_proto_klara_mx_v1_mail_proto_enumTypes[1]
}

func (x MailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailType.Descriptor instead.
func (MailType) EnumDescriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{1}
}

// Ref: https://www.rfc-editor.org/rfc/rfc2822#section-3.4
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mailbox identifier
	// Ref: https://www.rfc-editor.org/rfc/rfc2822#section-3.4.1
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Display name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MIME type
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type MailSendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  *Address               `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To    []*Address             `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc    []*Address             `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc   []*Address             `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// See https://www.rfc-editor.org/rfc/rfc2822#section-2.1.1
	Subject       string     `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       []*Message `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailSendRequest) Reset() {
	*x = MailSendRequest{}
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailSendRequest) ProtoMessage() {}

func (x *MailSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailSendRequest.ProtoReflect.Descriptor instead.
func (*MailSendRequest) Descriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{2}
}

func (x *MailSendRequest) GetFrom() *Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MailSendRequest) GetTo() []*Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MailSendRequest) GetCc() []*Address {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *MailSendRequest) GetBcc() []*Address {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *MailSendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailSendRequest) GetContent() []*Message {
	if x != nil {
		return x.Content
	}
	return nil
}

type MailSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailSendResponse) Reset() {
	*x = MailSendResponse{}
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailSendResponse) ProtoMessage() {}

func (x *MailSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klara_mx_v1_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailSendResponse.ProtoReflect.Descriptor instead.
func (*MailSendResponse) Descriptor() ([]byte, []int) {
	return file_proto_klara_mx_v1_mail_proto_rawDescGZIP(), []int{3}
}

var File_proto_klara_mx_v1_mail_proto protoreflect.FileDescriptor

const file_proto_klara_mx_v1_mail_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/klara/mx/v1/mail.proto\x12\vklara.mx.v1\"3\n" +
	"\aAddress\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\x87\x02\n" +
	"\x0fMailSendRequest\x12-\n" +
	"\x04from\x18\x01 \x01(\v2\x14.klara.mx.v1.AddressH\x00R\x04from\x88\x01\x01\x12$\n" +
	"\x02to\x18\x02 \x03(\v2\x14.klara.mx.v1.AddressR\x02to\x12$\n" +
	"\x02cc\x18\x03 \x03(\v2\x14.klara.mx.v1.AddressR\x02cc\x12&\n" +
	"\x03bcc\x18\x04 \x03(\v2\x14.klara.mx.v1.AddressR\x03bcc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12.\n" +
	"\acontent\x18\x06 \x03(\v2\x14.klara.mx.v1.MessageR\acontentB\a\n" +
	"\x05_from\"\x12\n" +
	"\x10MailSendResponse*[\n" +
	"\n" +
	"MailStatus\x12\x10\n" +
	"\fmail_pending\x10\x00\x12\x13\n" +
	"\x0fmail_processing\x10\x01\x12\r\n" +
	"\tmail_done\x10\x02\x12\x17\n" +
	"\n" +
	"mail_error\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*P\n" +
	"\bMailType\x12\x15\n" +
	"\x11mail_type_unknown\x10\x00\x12\x15\n" +
	"\x11mail_type_inbound\x10\x01\x12\x16\n" +
	"\x12mail_type_outbound\x10\x022K\n" +
	"\x04Mail\x12C\n" +
	"\x04Send\x12\x1c.klara.mx.v1.MailSendRequest\x1a\x1d.klara.mx.v1.MailSendResponseB&Z$go.tknz.dev/internal/klarapb;klarapbb\x06proto3"

var (
	file_proto_klara_mx_v1_mail_proto_rawDescOnce sync.Once
	file_proto_klara_mx_v1_mail_proto_rawDescData []byte
)

func file_proto_klara_mx_v1_mail_proto_rawDescGZIP() []byte {
	file_proto_klara_mx_v1_mail_proto_rawDescOnce.Do(func() {
		file_proto_klara_mx_v1_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_klara_mx_v1_mail_proto_rawDesc), len(file_proto_klara_mx_v1_mail_proto_rawDesc)))
	})
	return file_proto_klara_mx_v1_mail_proto_rawDescData
}

var file_proto_klara_mx_v1_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_klara_mx_v1_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_klara_mx_v1_mail_proto_goTypes = []any{
	(MailStatus)(0),          // 0: klara.mx.v1.MailStatus
	(MailType)(0),            // 1: klara.mx.v1.MailType
	(*Address)(nil),          // 2: klara.mx.v1.Address
	(*Message)(nil),          // 3: klara.mx.v1.Message
	(*MailSendRequest)(nil),  // 4: klara.mx.v1.MailSendRequest
	(*MailSendResponse)(nil), // 5: klara.mx.v1.MailSendResponse
}
var file_proto_klara_mx_v1_mail_proto_depIdxs = []int32{
	2, // 0: klara.mx.v1.MailSendRequest.from:type_name -> klara.mx.v1.Address
	2, // 1: klara.mx.v1.MailSendRequest.to:type_name -> klara.mx.v1.Address
	2, // 2: klara.mx.v1.MailSendRequest.cc:type_name -> klara.mx.v1.Address
	2, // 3: klara.mx.v1.MailSendRequest.bcc:type_name -> klara.mx.v1.Address
	3, // 4: klara.mx.v1.MailSendRequest.content:type_name -> klara.mx.v1.Message
	4, // 5: klara.mx.v1.Mail.Send:input_type -> klara.mx.v1.MailSendRequest
	5, // 6: klara.mx.v1.Mail.Send:output_type -> klara.mx.v1.MailSendResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_klara_mx_v1_mail_proto_init() }
func file_proto_klara_mx_v1_mail_proto_init() {
	if File_proto_klara_mx_v1_mail_proto != nil {
		return
	}
	file_proto_klara_mx_v1_mail_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_klara_mx_v1_mail_proto_rawDesc), len(file_proto_klara_mx_v1_mail_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_klara_mx_v1_mail_proto_goTypes,
		DependencyIndexes: file_proto_klara_mx_v1_mail_proto_depIdxs,
		EnumInfos:         file_proto_klara_mx_v1_mail_proto_enumTypes,
		MessageInfos:      file_proto_klara_mx_v1_mail_proto_msgTypes,
	}.Build()
	File_proto_klara_mx_v1_mail_proto = out.File
	file_proto_klara_mx_v1_mail_proto_goTypes = nil
	file_proto_klara_mx_v1_mail_proto_depIdxs = nil
}
