// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: proto/tknz/detail/cipher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cipher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KmsKey        string                 `protobuf:"bytes,1,opt,name=kms_key,json=kmsKey,proto3" json:"kms_key,omitempty"`
	KmsKeyVersion string                 `protobuf:"bytes,2,opt,name=kms_key_version,json=kmsKeyVersion,proto3" json:"kms_key_version,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cipher) Reset() {
	*x = Cipher{}
	mi := &file_proto_tknz_detail_cipher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cipher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cipher) ProtoMessage() {}

func (x *Cipher) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tknz_detail_cipher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cipher.ProtoReflect.Descriptor instead.
func (*Cipher) Descriptor() ([]byte, []int) {
	return file_proto_tknz_detail_cipher_proto_rawDescGZIP(), []int{0}
}

func (x *Cipher) GetKmsKey() string {
	if x != nil {
		return x.KmsKey
	}
	return ""
}

func (x *Cipher) GetKmsKeyVersion() string {
	if x != nil {
		return x.KmsKeyVersion
	}
	return ""
}

func (x *Cipher) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_proto_tknz_detail_cipher_proto protoreflect.FileDescriptor

const file_proto_tknz_detail_cipher_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/tknz/detail/cipher.proto\x12\vtknz.detail\"i\n" +
	"\x06Cipher\x12\x17\n" +
	"\akms_key\x18\x01 \x01(\tR\x06kmsKey\x12&\n" +
	"\x0fkms_key_version\x18\x02 \x01(\tR\rkmsKeyVersion\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertextB\x19Z\x17go.tknz.dev/internal/pbb\x06proto3"

var (
	file_proto_tknz_detail_cipher_proto_rawDescOnce sync.Once
	file_proto_tknz_detail_cipher_proto_rawDescData []byte
)

func file_proto_tknz_detail_cipher_proto_rawDescGZIP() []byte {
	file_proto_tknz_detail_cipher_proto_rawDescOnce.Do(func() {
		file_proto_tknz_detail_cipher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tknz_detail_cipher_proto_rawDesc), len(file_proto_tknz_detail_cipher_proto_rawDesc)))
	})
	return file_proto_tknz_detail_cipher_proto_rawDescData
}

var file_proto_tknz_detail_cipher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tknz_detail_cipher_proto_goTypes = []any{
	(*Cipher)(nil), // 0: tknz.detail.Cipher
}
var file_proto_tknz_detail_cipher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tknz_detail_cipher_proto_init() }
func file_proto_tknz_detail_cipher_proto_init() {
	if File_proto_tknz_detail_cipher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tknz_detail_cipher_proto_rawDesc), len(file_proto_tknz_detail_cipher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tknz_detail_cipher_proto_goTypes,
		DependencyIndexes: file_proto_tknz_detail_cipher_proto_depIdxs,
		MessageInfos:      file_proto_tknz_detail_cipher_proto_msgTypes,
	}.Build()
	File_proto_tknz_detail_cipher_proto = out.File
	file_proto_tknz_detail_cipher_proto_goTypes = nil
	file_proto_tknz_detail_cipher_proto_depIdxs = nil
}
