// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: proto/tknz/detail/token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Token signature
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Key id used for the token signature
	Kid           string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_tknz_detail_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tknz_detail_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_tknz_detail_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Token) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Token) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

var File_proto_tknz_detail_token_proto protoreflect.FileDescriptor

const file_proto_tknz_detail_token_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/tknz/detail/token.proto\x12\vtknz.detail\"M\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kidB\x19Z\x17go.tknz.dev/internal/pbb\x06proto3"

var (
	file_proto_tknz_detail_token_proto_rawDescOnce sync.Once
	file_proto_tknz_detail_token_proto_rawDescData []byte
)

func file_proto_tknz_detail_token_proto_rawDescGZIP() []byte {
	file_proto_tknz_detail_token_proto_rawDescOnce.Do(func() {
		file_proto_tknz_detail_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tknz_detail_token_proto_rawDesc), len(file_proto_tknz_detail_token_proto_rawDesc)))
	})
	return file_proto_tknz_detail_token_proto_rawDescData
}

var file_proto_tknz_detail_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tknz_detail_token_proto_goTypes = []any{
	(*Token)(nil), // 0: tknz.detail.Token
}
var file_proto_tknz_detail_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tknz_detail_token_proto_init() }
func file_proto_tknz_detail_token_proto_init() {
	if File_proto_tknz_detail_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tknz_detail_token_proto_rawDesc), len(file_proto_tknz_detail_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tknz_detail_token_proto_goTypes,
		DependencyIndexes: file_proto_tknz_detail_token_proto_depIdxs,
		MessageInfos:      file_proto_tknz_detail_token_proto_msgTypes,
	}.Build()
	File_proto_tknz_detail_token_proto = out.File
	file_proto_tknz_detail_token_proto_goTypes = nil
	file_proto_tknz_detail_token_proto_depIdxs = nil
}
