// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/felk/idaas/v1/authn.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdnStatus int32

const (
	IdnStatus_idn_pending   IdnStatus = 0
	IdnStatus_idn_active    IdnStatus = 1
	IdnStatus_idn_suspended IdnStatus = -1
	IdnStatus_idn_deleted   IdnStatus = -2
)

// Enum value maps for IdnStatus.
var (
	IdnStatus_name = map[int32]string{
		0:  "idn_pending",
		1:  "idn_active",
		-1: "idn_suspended",
		-2: "idn_deleted",
	}
	IdnStatus_value = map[string]int32{
		"idn_pending":   0,
		"idn_active":    1,
		"idn_suspended": -1,
		"idn_deleted":   -2,
	}
)

func (x IdnStatus) Enum() *IdnStatus {
	p := new(IdnStatus)
	*p = x
	return p
}

func (x IdnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_felk_idaas_v1_authn_proto_enumTypes[0].Descriptor()
}

func (IdnStatus) Type() protoreflect.EnumType {
	return &file_proto_felk_idaas_v1_authn_proto_enumTypes[0]
}

func (x IdnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdnStatus.Descriptor instead.
func (IdnStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_authn_proto_rawDescGZIP(), []int{0}
}

type Idn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        IdnStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=felk.idaas.v1.IdnStatus" json:"status,omitempty"`
	SpaceId       string                 `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Login         string                 `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Email         *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Picture       *string                `protobuf:"bytes,7,opt,name=picture,proto3,oneof" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idn) Reset() {
	*x = Idn{}
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idn) ProtoMessage() {}

func (x *Idn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idn.ProtoReflect.Descriptor instead.
func (*Idn) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_authn_proto_rawDescGZIP(), []int{0}
}

func (x *Idn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Idn) GetStatus() IdnStatus {
	if x != nil {
		return x.Status
	}
	return IdnStatus_idn_pending
}

func (x *Idn) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Idn) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Idn) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Idn) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Idn) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

type AuthnCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access token to validate
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// App ID, required if validating federated identity tokens
	AppId         *string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnCheckRequest) Reset() {
	*x = AuthnCheckRequest{}
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnCheckRequest) ProtoMessage() {}

func (x *AuthnCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnCheckRequest.ProtoReflect.Descriptor instead.
func (*AuthnCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_authn_proto_rawDescGZIP(), []int{1}
}

func (x *AuthnCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthnCheckRequest) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

type AuthnCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the check was successful or not
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Identity information if the check was successful
	Idn           *Idn `protobuf:"bytes,2,opt,name=idn,proto3,oneof" json:"idn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnCheckResponse) Reset() {
	*x = AuthnCheckResponse{}
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnCheckResponse) ProtoMessage() {}

func (x *AuthnCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnCheckResponse.ProtoReflect.Descriptor instead.
func (*AuthnCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_authn_proto_rawDescGZIP(), []int{2}
}

func (x *AuthnCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthnCheckResponse) GetIdn() *Idn {
	if x != nil {
		return x.Idn
	}
	return nil
}

var File_proto_felk_idaas_v1_authn_proto protoreflect.FileDescriptor

const file_proto_felk_idaas_v1_authn_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/felk/idaas/v1/authn.proto\x12\rfelk.idaas.v1\"\xea\x01\n" +
	"\x03Idn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.felk.idaas.v1.IdnStatusR\x06status\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1d\n" +
	"\apicture\x18\a \x01(\tH\x02R\apicture\x88\x01\x01B\b\n" +
	"\x06_emailB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_picture\"P\n" +
	"\x11AuthnCheckRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01B\t\n" +
	"\a_app_id\"W\n" +
	"\x12AuthnCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\x03idn\x18\x02 \x01(\v2\x12.felk.idaas.v1.IdnH\x00R\x03idn\x88\x01\x01B\x06\n" +
	"\x04_idn*b\n" +
	"\tIdnStatus\x12\x0f\n" +
	"\vidn_pending\x10\x00\x12\x0e\n" +
	"\n" +
	"idn_active\x10\x01\x12\x1a\n" +
	"\ridn_suspended\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vidn_deleted\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x012U\n" +
	"\x05Authn\x12L\n" +
	"\x05Check\x12 .felk.idaas.v1.AuthnCheckRequest\x1a!.felk.idaas.v1.AuthnCheckResponseB\x1dZ\x1bgithub.com/felk-ai/idaas/pbb\x06proto3"

var (
	file_proto_felk_idaas_v1_authn_proto_rawDescOnce sync.Once
	file_proto_felk_idaas_v1_authn_proto_rawDescData []byte
)

func file_proto_felk_idaas_v1_authn_proto_rawDescGZIP() []byte {
	file_proto_felk_idaas_v1_authn_proto_rawDescOnce.Do(func() {
		file_proto_felk_idaas_v1_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_felk_idaas_v1_authn_proto_rawDesc), len(file_proto_felk_idaas_v1_authn_proto_rawDesc)))
	})
	return file_proto_felk_idaas_v1_authn_proto_rawDescData
}

var file_proto_felk_idaas_v1_authn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_felk_idaas_v1_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_felk_idaas_v1_authn_proto_goTypes = []any{
	(IdnStatus)(0),             // 0: felk.idaas.v1.IdnStatus
	(*Idn)(nil),                // 1: felk.idaas.v1.Idn
	(*AuthnCheckRequest)(nil),  // 2: felk.idaas.v1.AuthnCheckRequest
	(*AuthnCheckResponse)(nil), // 3: felk.idaas.v1.AuthnCheckResponse
}
var file_proto_felk_idaas_v1_authn_proto_depIdxs = []int32{
	0, // 0: felk.idaas.v1.Idn.status:type_name -> felk.idaas.v1.IdnStatus
	1, // 1: felk.idaas.v1.AuthnCheckResponse.idn:type_name -> felk.idaas.v1.Idn
	2, // 2: felk.idaas.v1.Authn.Check:input_type -> felk.idaas.v1.AuthnCheckRequest
	3, // 3: felk.idaas.v1.Authn.Check:output_type -> felk.idaas.v1.AuthnCheckResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_felk_idaas_v1_authn_proto_init() }
func file_proto_felk_idaas_v1_authn_proto_init() {
	if File_proto_felk_idaas_v1_authn_proto != nil {
		return
	}
	file_proto_felk_idaas_v1_authn_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_felk_idaas_v1_authn_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_felk_idaas_v1_authn_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_felk_idaas_v1_authn_proto_rawDesc), len(file_proto_felk_idaas_v1_authn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_felk_idaas_v1_authn_proto_goTypes,
		DependencyIndexes: file_proto_felk_idaas_v1_authn_proto_depIdxs,
		EnumInfos:         file_proto_felk_idaas_v1_authn_proto_enumTypes,
		MessageInfos:      file_proto_felk_idaas_v1_authn_proto_msgTypes,
	}.Build()
	File_proto_felk_idaas_v1_authn_proto = out.File
	file_proto_felk_idaas_v1_authn_proto_goTypes = nil
	file_proto_felk_idaas_v1_authn_proto_depIdxs = nil
}
