// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/felk/idaas/v1/authn.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Authn_Check_FullMethodName = "/felk.idaas.v1.Authn/Check"
)

// AuthnClient is the client API for Authn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthnClient interface {
	Check(ctx context.Context, in *AuthnCheckRequest, opts ...grpc.CallOption) (*AuthnCheckResponse, error)
}

type authnClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthnClient(cc grpc.ClientConnInterface) AuthnClient {
	return &authnClient{cc}
}

func (c *authnClient) Check(ctx context.Context, in *AuthnCheckRequest, opts ...grpc.CallOption) (*AuthnCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthnCheckResponse)
	err := c.cc.Invoke(ctx, Authn_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthnServer is the server API for Authn service.
// All implementations must embed UnimplementedAuthnServer
// for forward compatibility.
type AuthnServer interface {
	Check(context.Context, *AuthnCheckRequest) (*AuthnCheckResponse, error)
	mustEmbedUnimplementedAuthnServer()
}

// UnimplementedAuthnServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthnServer struct{}

func (UnimplementedAuthnServer) Check(context.Context, *AuthnCheckRequest) (*AuthnCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAuthnServer) mustEmbedUnimplementedAuthnServer() {}
func (UnimplementedAuthnServer) testEmbeddedByValue()               {}

// UnsafeAuthnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthnServer will
// result in compilation errors.
type UnsafeAuthnServer interface {
	mustEmbedUnimplementedAuthnServer()
}

func RegisterAuthnServer(s grpc.ServiceRegistrar, srv AuthnServer) {
	// If the following call pancis, it indicates UnimplementedAuthnServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authn_ServiceDesc, srv)
}

func _Authn_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthnCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authn_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServer).Check(ctx, req.(*AuthnCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authn_ServiceDesc is the grpc.ServiceDesc for Authn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "felk.idaas.v1.Authn",
	HandlerType: (*AuthnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Authn_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/felk/idaas/v1/authn.proto",
}
