// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/felk/idaas/v1/spaces.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Space struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_spaces_proto_rawDescGZIP(), []int{0}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type SpacesCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpacesCreateRequest) Reset() {
	*x = SpacesCreateRequest{}
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpacesCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpacesCreateRequest) ProtoMessage() {}

func (x *SpacesCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpacesCreateRequest.ProtoReflect.Descriptor instead.
func (*SpacesCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_spaces_proto_rawDescGZIP(), []int{1}
}

func (x *SpacesCreateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type SpacesCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         *Space                 `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpacesCreateResponse) Reset() {
	*x = SpacesCreateResponse{}
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpacesCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpacesCreateResponse) ProtoMessage() {}

func (x *SpacesCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_felk_idaas_v1_spaces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpacesCreateResponse.ProtoReflect.Descriptor instead.
func (*SpacesCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_felk_idaas_v1_spaces_proto_rawDescGZIP(), []int{2}
}

func (x *SpacesCreateResponse) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

var File_proto_felk_idaas_v1_spaces_proto protoreflect.FileDescriptor

const file_proto_felk_idaas_v1_spaces_proto_rawDesc = "" +
	"\n" +
	" proto/felk/idaas/v1/spaces.proto\x12\rfelk.idaas.v1\"+\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\")\n" +
	"\x13SpacesCreateRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"B\n" +
	"\x14SpacesCreateResponse\x12*\n" +
	"\x05space\x18\x01 \x01(\v2\x14.felk.idaas.v1.SpaceR\x05space2[\n" +
	"\x06Spaces\x12Q\n" +
	"\x06Create\x12\".felk.idaas.v1.SpacesCreateRequest\x1a#.felk.idaas.v1.SpacesCreateResponseB\x1dZ\x1bgithub.com/felk-ai/idaas/pbb\x06proto3"

var (
	file_proto_felk_idaas_v1_spaces_proto_rawDescOnce sync.Once
	file_proto_felk_idaas_v1_spaces_proto_rawDescData []byte
)

func file_proto_felk_idaas_v1_spaces_proto_rawDescGZIP() []byte {
	file_proto_felk_idaas_v1_spaces_proto_rawDescOnce.Do(func() {
		file_proto_felk_idaas_v1_spaces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_felk_idaas_v1_spaces_proto_rawDesc), len(file_proto_felk_idaas_v1_spaces_proto_rawDesc)))
	})
	return file_proto_felk_idaas_v1_spaces_proto_rawDescData
}

var file_proto_felk_idaas_v1_spaces_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_felk_idaas_v1_spaces_proto_goTypes = []any{
	(*Space)(nil),                // 0: felk.idaas.v1.Space
	(*SpacesCreateRequest)(nil),  // 1: felk.idaas.v1.SpacesCreateRequest
	(*SpacesCreateResponse)(nil), // 2: felk.idaas.v1.SpacesCreateResponse
}
var file_proto_felk_idaas_v1_spaces_proto_depIdxs = []int32{
	0, // 0: felk.idaas.v1.SpacesCreateResponse.space:type_name -> felk.idaas.v1.Space
	1, // 1: felk.idaas.v1.Spaces.Create:input_type -> felk.idaas.v1.SpacesCreateRequest
	2, // 2: felk.idaas.v1.Spaces.Create:output_type -> felk.idaas.v1.SpacesCreateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_felk_idaas_v1_spaces_proto_init() }
func file_proto_felk_idaas_v1_spaces_proto_init() {
	if File_proto_felk_idaas_v1_spaces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_felk_idaas_v1_spaces_proto_rawDesc), len(file_proto_felk_idaas_v1_spaces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_felk_idaas_v1_spaces_proto_goTypes,
		DependencyIndexes: file_proto_felk_idaas_v1_spaces_proto_depIdxs,
		MessageInfos:      file_proto_felk_idaas_v1_spaces_proto_msgTypes,
	}.Build()
	File_proto_felk_idaas_v1_spaces_proto = out.File
	file_proto_felk_idaas_v1_spaces_proto_goTypes = nil
	file_proto_felk_idaas_v1_spaces_proto_depIdxs = nil
}
