// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/felk/idaas/v1/spaces.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spaces_Create_FullMethodName = "/felk.idaas.v1.Spaces/Create"
)

// SpacesClient is the client API for Spaces service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpacesClient interface {
	Create(ctx context.Context, in *SpacesCreateRequest, opts ...grpc.CallOption) (*SpacesCreateResponse, error)
}

type spacesClient struct {
	cc grpc.ClientConnInterface
}

func NewSpacesClient(cc grpc.ClientConnInterface) SpacesClient {
	return &spacesClient{cc}
}

func (c *spacesClient) Create(ctx context.Context, in *SpacesCreateRequest, opts ...grpc.CallOption) (*SpacesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpacesCreateResponse)
	err := c.cc.Invoke(ctx, Spaces_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpacesServer is the server API for Spaces service.
// All implementations must embed UnimplementedSpacesServer
// for forward compatibility.
type SpacesServer interface {
	Create(context.Context, *SpacesCreateRequest) (*SpacesCreateResponse, error)
	mustEmbedUnimplementedSpacesServer()
}

// UnimplementedSpacesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpacesServer struct{}

func (UnimplementedSpacesServer) Create(context.Context, *SpacesCreateRequest) (*SpacesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSpacesServer) mustEmbedUnimplementedSpacesServer() {}
func (UnimplementedSpacesServer) testEmbeddedByValue()                {}

// UnsafeSpacesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpacesServer will
// result in compilation errors.
type UnsafeSpacesServer interface {
	mustEmbedUnimplementedSpacesServer()
}

func RegisterSpacesServer(s grpc.ServiceRegistrar, srv SpacesServer) {
	// If the following call pancis, it indicates UnimplementedSpacesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spaces_ServiceDesc, srv)
}

func _Spaces_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpacesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spaces_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacesServer).Create(ctx, req.(*SpacesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Spaces_ServiceDesc is the grpc.ServiceDesc for Spaces service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spaces_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "felk.idaas.v1.Spaces",
	HandlerType: (*SpacesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Spaces_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/felk/idaas/v1/spaces.proto",
}
